Parameters:
  SecurityGroupMaskLambdaArn:
    Description: The ARN of the custom config rule lambda.
    Type: String
  MasterAccountID:
    Description: The master account.
    Type: String
    Default: 739846873405
  pRegion:
    Description: The region.
    Type: String
    Default: !Ref "AWS::Region"
Resources:
  CustomRuleForSecurityGroup:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: CustomRuleForSecurityGroup
      Scope:
        ComplianceResourceTypes:
          - "AWS::EC2::SecurityGroup"
      Source:
        Owner: "CUSTOM_LAMBDA"
        SourceDetails:
          -
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier:
          Ref: SecurityGroupMaskLambdaArn
  SecurityGroupRemediation:
    DependsOn: CustomRuleForSecurityGroup
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: CustomRuleForSecurityGroup
      ResourceType: "AWS::EC2::SecurityGroup"
      TargetId: !Sub "arn:aws:ssm:${pRegion}:${MasterAccountID}:document/RemediateOverlyPermissiveSGIngressRule"
      TargetType: "SSM_DOCUMENT"
      Parameters:
        SecurityGroup:
          ResourceValue:
            Value: "RESOURCE_ID"
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !Sub "arn:aws:iam::${MasterAccountID}:role/AutomationRole"
        MasterAccountID:
          StaticValue:
            Values:
              - !Sub "${MasterAccountID}"  
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Automatic: True
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 600